// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/ffi_plugin_look.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class FfiPluginLookBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FfiPluginLookBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FfiPluginLookBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// A very short-lived native function.
  ///
  /// For very short-lived functions, it is fine to call them on the main isolate.
  /// They will block the Dart execution while running the native function, so
  /// only do this for native functions which are guaranteed to be short-lived.
  int sum(int a, int b) {
    return _sum(a, b);
  }

  late final _sumPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('sum');
  late final _sum = _sumPtr.asFunction<int Function(int, int)>();

  /// A longer lived native function, which occupies the thread calling it.
  ///
  /// Do not call these kind of native functions in the main isolate. They will
  /// block Dart execution. This will cause dropped frames in Flutter applications.
  /// Instead, call these native functions on a separate isolate.
  int sum_long_running(int a, int b) {
    return _sum_long_running(a, b);
  }

  late final _sum_long_runningPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>(
        'sum_long_running',
      );
  late final _sum_long_running = _sum_long_runningPtr
      .asFunction<int Function(int, int)>();

  /// Multiplies two square matrices of size `dimension` x `dimension`.
  ///
  /// Matrices are passed in row-major order and the result buffer must have
  /// space for `dimension * dimension` doubles.
  void multiply_matrices(
    ffi.Pointer<ffi.Double> a,
    ffi.Pointer<ffi.Double> b,
    ffi.Pointer<ffi.Double> result,
    int dimension,
  ) {
    return _multiply_matrices(a, b, result, dimension);
  }

  late final _multiply_matricesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Double>,
            ffi.Pointer<ffi.Double>,
            ffi.Pointer<ffi.Double>,
            ffi.Int,
          )
        >
      >('multiply_matrices');
  late final _multiply_matrices = _multiply_matricesPtr
      .asFunction<
        void Function(
          ffi.Pointer<ffi.Double>,
          ffi.Pointer<ffi.Double>,
          ffi.Pointer<ffi.Double>,
          int,
        )
      >();

  /// Applies a grayscale filter to an RGBA buffer in-place.
  void apply_grayscale_filter(
    ffi.Pointer<ffi.Uint8> rgba_pixels,
    int width,
    int height,
  ) {
    return _apply_grayscale_filter(rgba_pixels, width, height);
  }

  late final _apply_grayscale_filterPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
            ffi.Int,
          )
        >
      >('apply_grayscale_filter');
  late final _apply_grayscale_filter = _apply_grayscale_filterPtr
      .asFunction<void Function(ffi.Pointer<ffi.Uint8>, int, int)>();
}
